services:

  #RE Cluster - Node 1
  re1:
    image: redislabs/redis:latest
    container_name: re1
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - "12000:12000"
      - "13000:13000"
      - "8443:8443"
      - "9443:9443"
    networks:
      re_cluster:
        ipv4_address: 192.168.20.2

  #RE Cluster - Node 2
  re2:
    image: redislabs/redis:latest
    container_name: re2
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    networks:
      re_cluster:
        ipv4_address: 192.168.20.3

  #RE Cluster - Node 3
  re3:
    image: redislabs/redis:latest
    container_name: re3
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    networks:
      re_cluster:
        ipv4_address: 192.168.20.4

  postgres:
    image: debezium/example-postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    profiles: ["postgres"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.5
  
  mysql:
    image: debezium/example-mysql:latest
    restart: on-failure
    container_name: mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
    profiles: ["mysql"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.8

#Docker Networks
networks:
  re_cluster:
    name: re_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
