services:

  #RE Cluster - Node 1
  re1:
    image: redislabs/redis:latest
    container_name: re1
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - "12000:12000"
      - "8443:8443"
      - "9443:9443"
    profiles: ["mysql", "postgres", "sqlserver", "oracle_lm", "oracle_xs"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.2

  #RE Cluster - Node 2
  re2:
    image: redislabs/redis:latest
    container_name: re2
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - "13000:13000"
    profiles: ["mysql", "postgres", "sqlserver", "oracle_lm", "oracle_xs"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.3

  #RE Cluster - Node 3
  re3:
    image: redislabs/redis:latest
    container_name: re3
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    profiles: ["mysql", "postgres", "sqlserver", "oracle_lm", "oracle_xs"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.4

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - $PWD/conf/postgres/scripts:/home/scripts
    command: [ "postgres", "-c", "wal_level=logical" ]
    profiles: ["postgres"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.5
  
  mysql:
    image: mysql:latest
    restart: on-failure
    container_name: mysql
    ports:
     - 3306:3306
    volumes:
      - $PWD/conf/mysql/conf.d:/etc/mysql/conf.d
      - $PWD/conf/mysql/scripts:/home/scripts
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_DATABASE=Chinook
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
    profiles: ["mysql"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.6

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
    volumes:
      - $PWD/conf/sqlserver/scripts:/home/scripts
    profiles: ["sqlserver"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.7

  oracle_lm:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle_lm
    ports:
     - 1521:1521
    environment:
     - ORACLE_SID=ORCLCDB 
     - ORACLE_EDITION=enterprise
     - ORACLE_PWD=Password1
     - INIT_SGA_SIZE=1024
     - INIT_PGA_SIZE=1024
    volumes:
      - $PWD/conf/oracle_lm/scripts:/opt/oracle/scripts/startup
    profiles: ["oracle_lm"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.8

  oracle_xs:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle_xs
    ports:
     - 1521:1521
    environment:
     - ORACLE_SID=ORCLCDB 
     - ORACLE_EDITION=enterprise
     - ORACLE_PWD=Password1
     - INIT_SGA_SIZE=1024
     - INIT_PGA_SIZE=1024
    volumes:
      - $PWD/conf/oracle_xs/scripts:/opt/oracle/scripts/startup
    profiles: ["oracle_xs"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.9

  debezium:
    build: 
      context: $PWD/conf/debezium
      args:
        INSTANT_CLIENT: $INSTANT_CLIENT 
    container_name: debezium
    volumes:
      - $PWD/conf/$SOURCE_DB/application.properties:/debezium/conf/application.properties
    profiles: ["debezium"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.20

#Docker Networks
networks:
  re_cluster:
    name: re_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24